#!/bin/bash

# Replace 'your_file.json' with the actual path to your JSON file
file_path="your_file.json"

# Get the total values for each label
total_critical=$(jq '.vulnerabilities.byseverity[] | select(.severity.label | ascii_downcase == "critical") | .total' "$file_path" | jq -s add)
total_high=$(jq '.vulnerabilities.byseverity[] | select(.severity.label | ascii_downcase == "high") | .total' "$file_path" | jq -s add)
total_medium=$(jq '.vulnerabilities.byseverity[] | select(.severity.label | ascii_downcase == "medium") | .total' "$file_path" | jq -s add)
total_low=$(jq '.vulnerabilities.byseverity[] | select(.severity.label | ascii_downcase == "low") | .total' "$file_path" | jq -s add)

# Print the results
echo "Total Critical: $total_critical"
echo "Total High: $total_high"
echo "Total Medium: $total_medium"
echo "Total Low: $total_low"



# Print the extracted values
echo "Result: $result"
echo "Scan URL: $scan_url"
echo "Vulnerabilities: Critical=$critical_count; High=$high_count; Medium=$medium_count; Low=$low_count"

slack_message=$(cat <<EOF
{
  "channel": "$YOUR_CHANNEL_ID",
  "text": "Sysdig Result: \"$result\"\nVulnerabilities: Critical=$critical_count; High=$high_count; Medium=$medium_count; Low=$low_count\nSysdigURL: \"$scan_url\""
}
EOF
)

