#!/bin/bash

# Function to extract the total value for a given label
function get_total_by_label() {
  local label=$1
  jq -r --arg label "$label" '.vulnerabilites.byseverity[] | select(.severity.lable | ascii_downcase == $label | ascii_upcase == $label) | .total' "$2" | awk '{ total += $1 } END { print total }'
}

# Replace 'your_file.json' with the actual path to your JSON file
file_path="your_file.json"

# Get the total values for each label
total_critical=$(get_total_by_label "critical" "$file_path")
total_high=$(get_total_by_label "High" "$file_path")
total_medium=$(get_total_by_label "Medium" "$file_path")
total_low=$(get_total_by_label "Low" "$file_path")

# Print the results
echo "Total Critical: $total_critical"
echo "Total High: $total_high"
echo "Total Medium: $total_medium"
echo "Total Low: $total_low"



# Print the extracted values
echo "Result: $result"
echo "Scan URL: $scan_url"
echo "Vulnerabilities: Critical=$critical_count; High=$high_count; Medium=$medium_count; Low=$low_count"

slack_message=$(cat <<EOF
{
  "channel": "$YOUR_CHANNEL_ID",
  "text": "Sysdig Result: \"$result\"\nVulnerabilities: Critical=$critical_count; High=$high_count; Medium=$medium_count; Low=$low_count\nSysdigURL: \"$scan_url\""
}
EOF
)

