#!/bin/bash

# Function to extract the value using grep, sed, and awk
extract_value() {
    grep -o "\"$1\":\"[^\"]*\"" "$2" | sed 's/.*":"//' | sed 's/"$//' | awk 'NR==1{print; exit}'
}

# Replace 'your_security_log_file.txt' with the path to your actual security log file
log_file_path="your_security_log_file.txt"

# Extract the result and scan URL and save them in variables
result=$(extract_value "result" "$log_file_path")
scan_url=$(extract_value "scan-result-url" "$log_file_path")

# Print the extracted values
echo "Result: $result"
echo "Scan URL: $scan_url"

# Replace YOUR_BEARER_TOKEN and YOUR_CHANNEL_ID with actual values
YOUR_BEARER_TOKEN="your_slack_bearer_token"
YOUR_CHANNEL_ID="your_slack_channel_id"

# Send Slack notification using jq for JSON formatting
slack_message=$(cat <<EOF
{
  "channel": "$YOUR_CHANNEL_ID",
  "text": "Sysdig Result: \"$result\"\nSysdigURL: \"$scan_url\""
}
EOF
)

curl -X POST -H "Authorization: Bearer $YOUR_BEARER_TOKEN" -H "Content-type: application/json" \
  -d "$slack_message" \
  https://slack.com/api/chat.postMessage
