---
- name: Install and Configure GitLab Runner
  hosts: your_target_hosts
  become: yes  # Use sudo to run commands as root

  tasks:
    - name: Set Environment Variables
      ansible.builtin.export:
        variable: GITLAB_DATA_DIR
        value: /home/gitlab-runner

    - name: Install Git
      ansible.builtin.yum:
        name: git
        state: present
        update_cache: yes

    - name: Download GitLab Runner
      ansible.builtin.get_url:
        url: https://gitlab-runner-downloads.s3.amazonaws.com/v12.4.1/binaries/gitlab-runner-linux-amd64
        dest: /usr/local/bin/gitlab-runner
        mode: '0755'

    - name: Create GitLab Runner User
      ansible.builtin.user:
        name: gitlab-runner
        comment: 'GitLab Runner'
        createhome: yes
        shell: /bin/bash

    - name: Create GitLab Data Directory
      ansible.builtin.file:
        path: "{{ GITLAB_DATA_DIR }}"
        state: directory
        owner: gitlab-runner
        group: root
        mode: '0777'

    - name: Install GitLab Runner
      ansible.builtin.command: gitlab-runner install --user eclapp --working-directory "{{ GITLAB_DATA_DIR }}"
      become: yes

    - name: Start GitLab Runner
      ansible.builtin.command: gitlab-runner start
      become: yes

    - name: Restart GitLab Runner
      ansible.builtin.command: gitlab-runner restart
      become: yes

    - name: Register GitLab Runner
      ansible.builtin.command: >
        gitlab-runner register \
          --non-interactive \
          --url "https://gitlab.verizon.com/" \
          --registration-token "CHANGE_TO_YOUR_GITLAB_CI_TOKEN" \
          --executor "shell" \
          --description "PROVIDE_DESCRIPTION" \
          --tag-list "PROVIDE_TAG" \
          --run-untagged "false" \
          --locked "false" \
          --access-level "not_protected"
      become: yes

    - name: Check GitLab Runner Status
      ansible.builtin.command: gitlab-runner status
      become: yes

    - name: Check GitLab Runner systemd unit status
      ansible.builtin.command: systemctl is-enabled gitlab-runner
      become: yes

    - name: Check Docker systemd unit status
      ansible.builtin.command: systemctl is-enabled docker
      become: yes

    - name: List GitLab Runners
      ansible.builtin.command: gitlab-runner list
      become: yes


---
- name: Create GitLab Data Directory
  hosts: your_target_host
  tasks:
    - name: Create GitLab Data Directory
      shell: mkdir -p "{{ GITLAB_DATA_DIR }}"
      become: yes
      become_user: gitlab-runner

- name: Install GitLab Runner
  hosts: your_target_host
  tasks:
    - name: Install GitLab Runner
      shell: gitlab-runner install
      become: yes
      become_user: gitlab-runner

- name: Start GitLab Runner
  hosts: your_target_host
  tasks:
    - name: Start GitLab Runner
      shell: gitlab-runner start
      become: yes
      become_user: gitlab-runner
      environment:
        HOME: "{{ GITLAB_DATA_DIR }}"

- name: Restart GitLab Runner
  hosts: your_target_host
  tasks:
    - name: Restart GitLab Runner
      shell: gitlab-runner restart
      become: yes
      become_user: gitlab-runner
      environment:
        HOME: "{{ GITLAB_DATA_DIR }}"
