---
- name: Replace Parameters in Shell Script
  hosts: your_target_hosts
  tasks:
    - name: Replace Parameter 1 in the Shell Script
      replace:
        path: /path/on/remote/host/example.sh  # Replace with the actual path on the remote host
        regexp: 'parameter1_placeholder'         # Replace with the placeholder in your script
        replace: 'new_value_for_parameter1'     # Replace with the new value you want

    - name: Replace Parameter 2 in the Shell Script
      replace:
        path: /path/on/remote/host/example.sh
        regexp: 'parameter2_placeholder'
        replace: 'new_value_for_parameter2'
